// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1632391063);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1632390823);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1632390943);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1632390853);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1632391183);
user_pref("browser.cache.disk.amount_written", 4985);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "cc778676-db89-4963-a89e-f60643dce09a");
user_pref("calendar.registry.cc778676-db89-4963-a89e-f60643dce09a.calendar-main-in-composite", true);
user_pref("calendar.registry.cc778676-db89-4963-a89e-f60643dce09a.disabled", true);
user_pref("calendar.registry.cc778676-db89-4963-a89e-f60643dce09a.name", "Home");
user_pref("calendar.registry.cc778676-db89-4963-a89e-f60643dce09a.type", "storage");
user_pref("calendar.registry.cc778676-db89-4963-a89e-f60643dce09a.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Johannesburg");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1632390805135");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1632391064);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210802223056");
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"eb465bb0-54ac-4eae-a98b-dc837e2b9752\",\"google@search.mozilla.org\":\"e1da8346-2c6d-4562-a701-87b7728cc636\",\"amazondotcom@search.mozilla.org\":\"4e0b2e06-c584-445d-b07e-16727ac31b0a\",\"bing@search.mozilla.org\":\"a98fedee-26d6-4fb4-ba00-5677f023a146\",\"ddg@search.mozilla.org\":\"3aec7dae-f320-4a5f-a4f4-4862970db977\",\"wikipedia@search.mozilla.org\":\"028e3562-5858-4883-8e1b-ff44c8187694\"}");
user_pref("idle.lastDailyNotification", 1632392071);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "abc4cf8b-2f69-4c50-9453-77a03228511");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.database.lastMaintenance", 1632392071);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("security.remote_settings.crlite_filters.checked", 1632390946);
user_pref("security.remote_settings.intermediates.checked", 1632390946);
user_pref("security.sandbox.plugin.tempDirSuffix", "31a0a668-006a-4423-9143-e41b3a3350ce");
user_pref("services.blocklist.pinning.checked", 1632390946);
user_pref("services.settings.clock_skew_seconds", -3);
user_pref("services.settings.last_etag", "\"1632383855598\"");
user_pref("services.settings.last_update_seconds", 1632390946);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1632390946);
user_pref("services.settings.main.hijack-blocklists.last_check", 1632390946);
user_pref("services.settings.main.language-dictionaries.last_check", 1632390946);
user_pref("services.settings.main.search-config.last_check", 1632390946);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1632390946);
user_pref("services.settings.main.sites-classification.last_check", 1632390946);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1632390946);
user_pref("services.settings.security.onecrl.checked", 1632390946);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1632392071);
user_pref("toolkit.telemetry.cachedClientID", "f15cf339-cd59-47d4-8e98-3d01e6a22f6c");
user_pref("toolkit.telemetry.previousBuildID", "20210802223056");
